Навбар, Регистрация, Аудитории, Группы объявлений
reddiridabl666/homework-selenium-2023-autumn pull request #1
Opened 2023-12-13 18:38 UTC by reddiridabl666

2023-12-13 18:53 UTC, Rioskill commented on hw/code/ui/fixtures.py
> +def create_account(config, credentials):
Это нужно?

2023-12-13 19:03 UTC, mihaillatyshov requested changes

2023-12-13 19:03 UTC, mihaillatyshov commented on hw/code/ui/locators/basic_locators.py
> +    GO_TO_ACCOUNT = (By.LINK_TEXT, "Перейти в кабинет")
Может пересекаться с футером

2023-12-13 20:05 UTC, Rioskill approved these changes
Аппрув

2023-12-13 20:17 UTC, mihaillatyshov approved these changes

2023-12-14 10:23 UTC, merged

2023-12-14 11:32 UTC, CyTb-On-Fire commented
Approve