Монетизация. Справка. Центр коммерции. Сайты
reddiridabl666/homework-selenium-2023-autumn pull request #2
Opened 2023-12-13 18:45 UTC by Rioskill

2023-12-13 19:15 UTC, mihaillatyshov requested changes

2023-12-13 19:15 UTC, mihaillatyshov commented on hw/code/ui/pages/base_page.py
> +    def click(self, locator, timeout=10000) -> WebElement:
Что по таймауту? )

2023-12-13 19:15 UTC, mihaillatyshov commented on hw/code/ui/pages/base_page.py
> +    def fill_in(self, locator, query, timeout=10000) -> WebElement:
Что по таймауту х2? )

2023-12-13 19:15 UTC, mihaillatyshov commented on runner_tests.sh
> +# pytest --log-cli-level=DEBUG -v hw/code -k "test_site_tab"
Уберем комментарии?

2023-12-13 19:17 UTC, reddiridabl666 commented on hw/code/test_partner.py
> +    authorize = False
У нас нет логики с Authorize в BasePage, можно убрать

2023-12-13 19:17 UTC, reddiridabl666 commented on hw/code/test_sites.py
> +        sites_page.fill_domain_input("")
Почему пустая строка?

2023-12-13 19:17 UTC, reddiridabl666 commented on hw/code/ui/locators/basic_locators.py
> +    PIXEL_ADDED_MODAL = (By.XPATH, '//h2[contains(text(), "Создан ID пикселя")]')
Локатор на h2 кажется нестабильным

2023-12-13 19:17 UTC, reddiridabl666 commented on hw/code/ui/wait_conditions.py
> +                "return false;                            "
Может, лучше многострочный литерал сделать, а не складывать строки?

2023-12-13 20:05 UTC, reddiridabl666 approved these changes

2023-12-13 20:18 UTC, mihaillatyshov approved these changes

2023-12-14 10:29 UTC, merged

2023-12-14 11:31 UTC, CyTb-On-Fire commented
Approve